// ==============================================================================
// REFINERY PROCESS MANAGEMENT SYSTEM (PRD-REF-001)
// Authentic Industrial Seed & Mock Data: Nisshin Deodorizer Plant & Lab
// Structured Consistent RFC-4122 Hierarchical UUID Schema
// ==============================================================================

import { 
  Plant, 
  Profile, 
  Product, 
  Tank, 
  SamplingPoint, 
  Parameter, 
  ParameterLimit, 
  ProductSpec, 
  ProcessSheet, 
  SampleReport, 
  Deviation, 
  RejectionReason, 
  AuditLogEntry 
} from '@/types/refinery';

export const INITIAL_PLANT: Plant = {
  id: 'PLT001',
  code: 'NISSHIN_DEOD',
  name: 'Nisshin Deodorizer Plant',
  timezone: 'Asia/Kuala_Lumpur',
  active: true,
};

export const INITIAL_PROFILES: Profile[] = [
  {
    id: 'OPR001',
    employee_no: 'OPR001',
    full_name: 'Ahmad Razak (Operator)',
    role: 'operator',
    status: 'active',
    active: true,
    password: 'password123',
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'SUP001',
    employee_no: 'SUP001',
    full_name: 'Chong Wei Lun (Supervisor)',
    role: 'supervisor',
    status: 'active',
    active: true,
    password: 'password123',
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'QCS001',
    employee_no: 'QCS001',
    full_name: 'Siti Nurhaliza (QC Staff)',
    role: 'qc_analyst',
    status: 'active',
    active: true,
    password: 'password123',
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'MGR001',
    employee_no: 'MGR001',
    full_name: 'Dr. Tan Keng Boon (Manager)',
    role: 'qc_manager',
    status: 'active',
    active: true,
    password: 'password123',
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'ADM001',
    employee_no: 'ADM001',
    full_name: 'Haris Iskandar (Administrator)',
    role: 'admin',
    status: 'active',
    active: true,
    password: 'password123',
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'USR001',
    employee_no: 'USR001',
    full_name: 'ISO Quality Auditor (User)',
    role: 'viewer',
    status: 'active',
    active: true,
    password: 'password123',
    created_at: '2026-01-10T00:00:00Z',
  },
  // Legacy aliases for backward compatibility
  {
    id: 'OPR001',
    employee_no: 'OPR001',
    full_name: 'Ahmad Razak (Operator)',
    role: 'operator',
    status: 'active',
    active: true,
    password: 'password123',
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'SUP001',
    employee_no: 'SUP001',
    full_name: 'Chong Wei Lun (Supervisor)',
    role: 'supervisor',
    status: 'active',
    active: true,
    password: 'password123',
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'QCS001',
    employee_no: 'QCS001',
    full_name: 'Siti Nurhaliza (QC Staff)',
    role: 'qc_analyst',
    status: 'active',
    active: true,
    password: 'password123',
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'MGR001',
    employee_no: 'MGR001',
    full_name: 'Dr. Tan Keng Boon (Manager)',
    role: 'qc_manager',
    status: 'active',
    active: true,
    password: 'password123',
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'ADM001',
    employee_no: 'ADM001',
    full_name: 'Haris Iskandar (Administrator)',
    role: 'admin',
    status: 'active',
    active: true,
    password: 'password123',
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'USR001',
    employee_no: 'USR001',
    full_name: 'ISO Quality Auditor (User)',
    role: 'viewer',
    status: 'active',
    active: true,
    password: 'password123',
    created_at: '2026-01-10T00:00:00Z',
  },
];

// All 44 Products from Appendix 18 with Hierarchical UUIDs (50000000-0000-0000-0000-000000000xxx)
export const INITIAL_PRODUCTS: Product[] = [
  { id: 'PRD001', code: 'CHOCOHI_357A_NPHO', name: 'Chocohi 357A NPHO', category: 'specialty', sort_order: 1, active: true },
  { id: 'PRD002', code: 'CHOCOHI_369A', name: 'Chocohi 369A', category: 'specialty', sort_order: 2, active: true },
  { id: 'PRD003', code: 'DAISY_SOFT_PM180602_I2', name: 'Daisy Soft PM180602 I2', category: 'olein', sort_order: 3, active: true },
  { id: 'PRD004', code: 'DF_20', name: 'DF 20', category: 'blend', sort_order: 4, active: true },
  { id: 'PRD005', code: 'FARM_COW_R2', name: 'Farm Cow R2', category: 'blend', sort_order: 5, active: true },
  { id: 'PRD006', code: 'G9', name: 'G9', category: 'blend', sort_order: 6, active: true },
  { id: 'PRD007', code: 'HPO_58', name: 'HPO 58', category: 'stearin', sort_order: 7, active: true },
  { id: 'PRD008', code: 'HPKO', name: 'HPKO', category: 'kernel', sort_order: 8, active: true },
  { id: 'PRD009', code: 'HPS_52', name: 'HPS 52', category: 'stearin', sort_order: 9, active: true },
  { id: 'PRD010', code: 'HPS_58', name: 'HPS 58', category: 'stearin', sort_order: 10, active: true },
  { id: 'PRD011', code: 'HYFAT_L1', name: 'Hyfat L1', category: 'specialty', sort_order: 11, active: true },
  { id: 'PRD012', code: 'HYFAT_K1_P', name: 'Hyfat K1 (P)', category: 'specialty', sort_order: 12, active: true },
  { id: 'PRD013', code: 'HYFAT_K1_B', name: 'Hyfat K1 (B)', category: 'specialty', sort_order: 13, active: true },
  { id: 'PRD014', code: 'PMF', name: 'PMF', category: 'specialty', sort_order: 14, active: true },
  { id: 'PRD015', code: 'PR_PMF', name: 'PR PMF', category: 'specialty', sort_order: 15, active: true },
  { id: 'PRD016', code: 'IEPMF', name: 'IEPMF', category: 'specialty', sort_order: 16, active: true },
  { id: 'PRD017', code: 'R_IEPMF', name: 'R. IEPMF', category: 'specialty', sort_order: 17, active: true },
  { id: 'PRD018', code: 'PR_IEPMF', name: 'PR IEPMF', category: 'specialty', sort_order: 18, active: true },
  { id: 'PRD019', code: 'KRIMWELL_IER', name: 'Krimwell IER', category: 'specialty', sort_order: 19, active: true },
  { id: 'PRD020', code: 'NATUREL_WOS', name: 'Naturel WOS', category: 'consumer', sort_order: 20, active: true },
  { id: 'PRD021', code: 'NATUREL_LITE', name: 'Naturel Lite', category: 'consumer', sort_order: 21, active: true },
  { id: 'PRD022', code: 'NATUREL_OLIVE', name: 'Naturel Olive', category: 'consumer', sort_order: 22, active: true },
  { id: 'PRD023', code: 'PASTRIFET_SK', name: 'Pastrifet SK', category: 'shortening', sort_order: 23, active: true },
  { id: 'PRD024', code: 'PL_56', name: 'PL 56', category: 'olein', sort_order: 24, active: true },
  { id: 'PRD025', code: 'PL_60', name: 'PL 60', category: 'olein', sort_order: 25, active: true },
  { id: 'PRD026', code: 'PL_65_MATSUYAMA', name: 'PL 65 Matsuyama', category: 'olein', sort_order: 26, active: true },
  { id: 'PRD027', code: 'PL_65_WAYIDEAL', name: 'PL 65 Wayideal', category: 'olein', sort_order: 27, active: true },
  { id: 'PRD028', code: 'PR_PL65', name: 'PR PL65', category: 'olein', sort_order: 28, active: true },
  { id: 'PRD029', code: 'NBD_PL65', name: 'NBD PL65', category: 'olein', sort_order: 29, active: true },
  { id: 'PRD030', code: 'PALM_FAT_BLEND', name: 'Palm Fat Blend', category: 'blend', sort_order: 30, active: true },
  { id: 'PRD031', code: 'RPMO', name: 'RPMO', category: 'olein', sort_order: 31, active: true },
  { id: 'PRD032', code: 'PR_PMO', name: 'PR PMO', category: 'olein', sort_order: 32, active: true },
  { id: 'PRD033', code: 'RSTN', name: 'RSTN', category: 'stearin', sort_order: 33, active: true },
  { id: 'PRD034', code: 'RSTN_S', name: 'RSTN (S)', category: 'stearin', sort_order: 34, active: true },
  { id: 'PRD035', code: 'RSTN_H', name: 'RSTN (H)', category: 'stearin', sort_order: 35, active: true },
  { id: 'PRD036', code: 'PR_STN', name: 'PR STN', category: 'stearin', sort_order: 36, active: true },
  { id: 'PRD037', code: 'PR_STN_S', name: 'PR STN (S)', category: 'stearin', sort_order: 37, active: true },
  { id: 'PRD038', code: 'PR_STN_H', name: 'PR STN (H)', category: 'stearin', sort_order: 38, active: true },
  { id: 'PRD039', code: 'RPKO', name: 'RPKO', category: 'kernel', sort_order: 39, active: true },
  { id: 'PRD040', code: 'RPKL', name: 'RPKL', category: 'kernel', sort_order: 40, active: true },
  { id: 'PRD041', code: 'SHORTENING', name: 'Shortening', category: 'shortening', sort_order: 41, active: true },
  { id: 'PRD042', code: 'SRIV60_FMF_SNAX', name: 'SRIV60 (FMF Snax)', category: 'specialty', sort_order: 42, active: true },
  { id: 'PRD043', code: 'SPLASH_OIL', name: 'Splash Oil', category: 'blend', sort_order: 43, active: true },
  { id: 'PRD044', code: 'FLUSH_OIL', name: 'Flush Oil', category: 'by-product', sort_order: 44, active: true },
  { id: 'PRD045', code: 'PFAD', name: 'PFAD', category: 'by-product', sort_order: 45, active: true },
];

export const DEFAULT_PRODUCT_ID = 'PRD026'; // PL 65 Matsuyama

// Tanks with Hierarchical UUIDs (20000000-0000-0000-0000-000000000xxx)
export const INITIAL_TANKS: Tank[] = [
  { id: 'TK001', plant_id: INITIAL_PLANT.id, code: 'TK-101A', kind: 'feed', active: true },
  { id: 'TK002', plant_id: INITIAL_PLANT.id, code: 'TK-101B', kind: 'feed', active: true },
  { id: 'TK003', plant_id: INITIAL_PLANT.id, code: 'TK-102', kind: 'feed', active: true },
  { id: 'TK004', plant_id: INITIAL_PLANT.id, code: 'TK-201A', kind: 'discharge', active: true },
  { id: 'TK005', plant_id: INITIAL_PLANT.id, code: 'TK-201B', kind: 'discharge', active: true },
  { id: 'TK006', plant_id: INITIAL_PLANT.id, code: 'TK-202', kind: 'discharge', active: true },
];

export const DEFAULT_FEED_TANK_ID = 'TK001';
export const DEFAULT_DISCHARGE_TANK_ID = 'TK004';

// Sampling Points with Hierarchical UUIDs (30000000-0000-0000-0000-000000000xxx)
export const INITIAL_SAMPLING_POINTS: SamplingPoint[] = [
  { id: 'SP001', plant_id: INITIAL_PLANT.id, name: 'Deodorizer Outlet Pipe (Header 4)', active: true },
  { id: 'SP002', plant_id: INITIAL_PLANT.id, name: 'Tray 7 Final Sampling Cock', active: true },
  { id: 'SP003', plant_id: INITIAL_PLANT.id, name: 'Cooler BC-101 Discharge Line', active: true },
  { id: 'SP004', plant_id: INITIAL_PLANT.id, name: 'Polishing Filter FP-101 Manifold', active: true },
  { id: 'SP005', plant_id: INITIAL_PLANT.id, name: 'Finished Oil Storage Inflow', active: true },
];

export const DEFAULT_SAMPLING_POINT_ID = 'SP001';

// Lab Parameters with Hierarchical UUIDs (40000000-0000-0000-0000-000000000xxx)
export const PARAM_IDS = {
  FFA:         'PAR001',
  H2O:         'PAR002',
  IV:          'PAR003',
  PV:          'PAR004',
  COLOUR_R:    'PAR005',
  COLOUR_Y:    'PAR006',
  ODOUR:       'PAR007',
  BPP:         'PAR008',
  SLIP_MELT:   'PAR009',
  CLOUD_POINT: 'PAR010',
  SOAP:        'PAR011',
  FAC_C12:     'PAR012',
  SFC:         'PAR013',
  TEMP:        'PAR014',
};

export const INITIAL_PARAMETERS: Parameter[] = [
  { id: PARAM_IDS.FFA, code: 'FFA', name: 'Free Fatty Acid (Palmitic)', unit: '%', decimals: 2, is_series: false, input_kind: 'numeric', sort_order: 1 },
  { id: PARAM_IDS.H2O, code: 'H2O', name: 'Moisture & Impurities', unit: '%', decimals: 3, is_series: false, input_kind: 'numeric', sort_order: 2 },
  { id: PARAM_IDS.IV, code: 'IV', name: 'Iodine Value (Wijs)', unit: 'g I₂/100g', decimals: 1, is_series: false, input_kind: 'numeric', sort_order: 3 },
  { id: PARAM_IDS.PV, code: 'PV', name: 'Peroxide Value', unit: 'meq/kg', decimals: 2, is_series: false, input_kind: 'numeric', sort_order: 4 },
  { id: PARAM_IDS.COLOUR_R, code: 'COLOUR_R', name: 'Colour Lovibond Red (5¼" cell)', unit: 'R', decimals: 1, is_series: false, input_kind: 'numeric', sort_order: 5 },
  { id: PARAM_IDS.COLOUR_Y, code: 'COLOUR_Y', name: 'Colour Lovibond Yellow (5¼" cell)', unit: 'Y', decimals: 1, is_series: false, input_kind: 'numeric', sort_order: 6 },
  { id: PARAM_IDS.ODOUR, code: 'ODOUR', name: 'Odour Assessment', unit: null, decimals: 0, is_series: false, input_kind: 'select', sort_order: 7 },
  { id: PARAM_IDS.BPP, code: 'BPP', name: 'Breakdown Product Point', unit: '°C', decimals: 1, is_series: false, input_kind: 'numeric', sort_order: 8 },
  { id: PARAM_IDS.SLIP_MELT, code: 'SLIP_MELT', name: 'Slip Melting Point', unit: '°C', decimals: 1, is_series: false, input_kind: 'numeric', sort_order: 9 },
  { id: PARAM_IDS.CLOUD_POINT, code: 'CLOUD_POINT', name: 'Cloud Point', unit: '°C', decimals: 1, is_series: false, input_kind: 'numeric', sort_order: 10 },
  { id: PARAM_IDS.SOAP, code: 'SOAP', name: 'Soap Content', unit: 'ppm', decimals: 1, is_series: false, input_kind: 'numeric', sort_order: 11 },
  { id: PARAM_IDS.FAC_C12, code: 'FAC_C12', name: 'Fatty Acid Composition C12:0', unit: '%', decimals: 2, is_series: false, input_kind: 'numeric', sort_order: 12 },
  { id: PARAM_IDS.SFC, code: 'SFC', name: 'Solid Fat Content (SFC)', unit: '%', decimals: 1, is_series: false, input_kind: 'numeric', sort_order: 13 },
  { id: PARAM_IDS.TEMP, code: 'TEMP', name: 'Temperature Series', unit: '-', decimals: 1, is_series: true, series_values: [10, 15, 20, 25, 30, 35, 40, 45, 50], input_kind: 'text', sort_order: 14 },
];

export const INITIAL_LIMITS: ParameterLimit[] = [
  { id: 'LIM001', plant_id: INITIAL_PLANT.id, field_key: 'vacuum_torr', hard_min: 0, hard_max: 760, soft_min: 1.0, soft_max: 4.5 },
  { id: 'LIM002', plant_id: INITIAL_PLANT.id, field_key: 'tray_1_temp_c', hard_min: 0, hard_max: 350, soft_min: 240, soft_max: 260 },
  { id: 'LIM003', plant_id: INITIAL_PLANT.id, field_key: 'tray_2_temp_c', hard_min: 0, hard_max: 350, soft_min: 245, soft_max: 262 },
  { id: 'LIM004', plant_id: INITIAL_PLANT.id, field_key: 'tray_3_temp_c', hard_min: 0, hard_max: 350, soft_min: 248, soft_max: 265 },
  { id: 'LIM005', plant_id: INITIAL_PLANT.id, field_key: 'tray_4_temp_c', hard_min: 0, hard_max: 350, soft_min: 250, soft_max: 268 },
  { id: 'LIM006', plant_id: INITIAL_PLANT.id, field_key: 'tray_5_temp_c', hard_min: 0, hard_max: 350, soft_min: 250, soft_max: 268 },
  { id: 'LIM007', plant_id: INITIAL_PLANT.id, field_key: 'tray_6_temp_c', hard_min: 0, hard_max: 350, soft_min: 235, soft_max: 250 },
  { id: 'LIM008', plant_id: INITIAL_PLANT.id, field_key: 'tray_7_temp_c', hard_min: 0, hard_max: 350, soft_min: 180, soft_max: 210 },
  { id: 'LIM009', plant_id: INITIAL_PLANT.id, field_key: 'bc101_water_in_c', hard_min: 0, hard_max: 150, soft_min: 28, soft_max: 34 },
  { id: 'LIM010', plant_id: INITIAL_PLANT.id, field_key: 'bc101_water_out_c', hard_min: 0, hard_max: 150, soft_min: 36, soft_max: 48 },
  { id: 'LIM011', plant_id: INITIAL_PLANT.id, field_key: 'chill_water_in_c', hard_min: 0, hard_max: 100, soft_min: 8, soft_max: 14 },
  { id: 'LIM012', plant_id: INITIAL_PLANT.id, field_key: 'chill_water_out_c', hard_min: 0, hard_max: 100, soft_min: 14, soft_max: 22 },
  { id: 'LIM013', plant_id: INITIAL_PLANT.id, field_key: 'booster_press_bar', hard_min: 0, hard_max: 60, soft_min: 8.0, soft_max: 12.0 },
  { id: 'LIM014', plant_id: INITIAL_PLANT.id, field_key: 'ejector_press_bar', hard_min: 0, hard_max: 60, soft_min: 8.0, soft_max: 12.0 },
  { id: 'LIM015', plant_id: INITIAL_PLANT.id, field_key: 'strip_steam_pct_of_oil', hard_min: 0, hard_max: 100, soft_min: 1.2, soft_max: 1.8 },
  { id: 'LIM016', plant_id: INITIAL_PLANT.id, field_key: 'fp101a_press_bar', hard_min: 0, hard_max: 20, soft_min: 1.5, soft_max: 4.5 },
  { id: 'LIM017', plant_id: INITIAL_PLANT.id, field_key: 'fp101b_press_bar', hard_min: 0, hard_max: 20, soft_min: 1.5, soft_max: 4.5 },
];

export const INITIAL_REJECTION_REASONS: RejectionReason[] = [
  { id: 'REJ001', code: 'FFA_HIGH', label: 'FFA above specification', active: true },
  { id: 'REJ002', code: 'H2O_HIGH', label: 'Moisture above specification', active: true },
  { id: 'REJ003', code: 'PV_HIGH', label: 'Peroxide value above specification', active: true },
  { id: 'REJ004', code: 'COLOUR_OUT', label: 'Colour out of specification', active: true },
  { id: 'REJ005', code: 'OFF_ODOUR', label: 'Off odour detected', active: true },
  { id: 'REJ006', code: 'SMP_OUT', label: 'Slip melting point out of range', active: true },
  { id: 'REJ007', code: 'CLOUD_OUT', label: 'Cloud point out of range', active: true },
  { id: 'REJ008', code: 'SFC_OUT', label: 'SFC profile out of range', active: true },
  { id: 'REJ009', code: 'SOAP_HIGH', label: 'Soap content above limit', active: true },
  { id: 'REJ010', code: 'IV_OUT', label: 'Iodine value out of range', active: true },
  { id: 'REJ011', code: 'CONTAMINATION', label: 'Cross-contamination suspected', active: true },
  { id: 'REJ012', code: 'WRONG_TANK', label: 'Wrong product in tank', active: true },
  { id: 'REJ013', code: 'SAMPLING_ERR', label: 'Sampling error, resample required', active: true },
];

// Product specifications for PL 65 Matsuyama (Product 26) with Consistent UUIDs
export const INITIAL_SPECS: ProductSpec[] = [
  { id: 'SPC001', product_id: DEFAULT_PRODUCT_ID, parameter_id: PARAM_IDS.FFA, max_value: 0.05, target_value: 0.03, effective_from: '2026-01-01' },
  { id: 'SPC002', product_id: DEFAULT_PRODUCT_ID, parameter_id: PARAM_IDS.H2O, max_value: 0.050, target_value: 0.025, effective_from: '2026-01-01' },
  { id: 'SPC003', product_id: DEFAULT_PRODUCT_ID, parameter_id: PARAM_IDS.IV, min_value: 64.0, max_value: 67.0, target_value: 65.2, effective_from: '2026-01-01' },
  { id: 'SPC004', product_id: DEFAULT_PRODUCT_ID, parameter_id: PARAM_IDS.PV, max_value: 1.00, target_value: 0.20, effective_from: '2026-01-01' },
  { id: 'SPC005', product_id: DEFAULT_PRODUCT_ID, parameter_id: PARAM_IDS.COLOUR_R, max_value: 2.5, target_value: 2.0, effective_from: '2026-01-01' },
  { id: 'SPC006', product_id: DEFAULT_PRODUCT_ID, parameter_id: PARAM_IDS.COLOUR_Y, max_value: 25.0, target_value: 20.0, effective_from: '2026-01-01' },
  { id: 'SPC007', product_id: DEFAULT_PRODUCT_ID, parameter_id: PARAM_IDS.CLOUD_POINT, max_value: 3.5, target_value: 2.8, effective_from: '2026-01-01' },
  { id: 'SPC008', product_id: DEFAULT_PRODUCT_ID, parameter_id: PARAM_IDS.SFC, min_value: 0.0, max_value: 60.0, target_value: 28.0, effective_from: '2026-01-01' },
  { id: 'SPC009', product_id: DEFAULT_PRODUCT_ID, parameter_id: PARAM_IDS.TEMP, series_key: 10, min_value: 48.0, max_value: 56.0, target_value: 52.0, effective_from: '2026-01-01' },
  { id: 'SPC010', product_id: DEFAULT_PRODUCT_ID, parameter_id: PARAM_IDS.TEMP, series_key: 20, min_value: 24.0, max_value: 30.0, target_value: 27.0, effective_from: '2026-01-01' },
  { id: 'SPC011', product_id: DEFAULT_PRODUCT_ID, parameter_id: PARAM_IDS.TEMP, series_key: 30, min_value: 6.0, max_value: 10.0, target_value: 8.0, effective_from: '2026-01-01' },
  { id: 'SPC012', product_id: DEFAULT_PRODUCT_ID, parameter_id: PARAM_IDS.TEMP, series_key: 35, max_value: 2.0, target_value: 0.5, effective_from: '2026-01-01' },
];

// 24-Hour Process Sheet for 2026-09-20 (Hierarchical UUID PR001)
export const INITIAL_SHEET: ProcessSheet = {
  id: 'PR001',
  plant_id: INITIAL_PLANT.id,
  shift_date: '2026-09-20',
  stripping_steam_pct: 1.5,
  set_steam_supply_bar: 3.0,
  status: 'verified',
  opened_by: 'OPR001',
  opened_by_name: 'Ahmad Razak',
  opened_at: '2026-09-20T06:55:00+08:00',
  verified_by: 'SUP001',
  verified_by_name: 'Chong Wei Lun',
  verified_at: '2026-09-20T19:30:00+08:00',
  entries: [
    {
      id: 'PL001',
      sheet_id: 'PR001',
      slot_index: 0,
      slot_label: '0700',
      slot_start: '2026-09-20T07:00:00+08:00',
      product_id: DEFAULT_PRODUCT_ID,
      product_name: 'PL 65 Matsuyama',
      oil_feed_rate_litre: 25000,
      deod_time_set_hr: 2.0,
      vacuum_torr: 2.4,
      tray_1_temp_c: 252.0,
      tray_2_temp_c: 256.4,
      tray_3_temp_c: 260.1,
      tray_4_temp_c: 264.5,
      tray_5_temp_c: 263.8,
      tray_6_temp_c: 242.0,
      tray_7_temp_c: 195.0,
      bc101_water_in_c: 30.5,
      bc101_water_out_c: 42.0,
      chill_water_in_c: 10.2,
      chill_water_out_c: 16.5,
      booster_press_bar: 9.8,
      ejector_press_bar: 10.1,
      strip_steam_pct_of_oil: 1.5,
      strip_steam_flow_kghr: 375.0,
      fp101a_press_bar: 2.2,
      fp101b_press_bar: 2.1,
      remarks: 'Start of shift. Plant running steady on PL 65.',
      no_production_reason: null,
      has_deviation: false,
      recorded_by: 'OPR001',
      recorded_by_name: 'Ahmad Razak',
      recorded_at: '2026-09-20T07:05:00+08:00',
    },
    {
      id: 'PL002',
      sheet_id: 'PR001',
      slot_index: 1,
      slot_label: '0800',
      slot_start: '2026-09-20T08:00:00+08:00',
      product_id: DEFAULT_PRODUCT_ID,
      product_name: 'PL 65 Matsuyama',
      oil_feed_rate_litre: 25100,
      deod_time_set_hr: 2.0,
      vacuum_torr: 2.5,
      tray_1_temp_c: 253.2,
      tray_2_temp_c: 257.0,
      tray_3_temp_c: 261.2,
      tray_4_temp_c: 265.1,
      tray_5_temp_c: 264.0,
      tray_6_temp_c: 242.5,
      tray_7_temp_c: 196.2,
      bc101_water_in_c: 31.0,
      bc101_water_out_c: 42.5,
      chill_water_in_c: 10.4,
      chill_water_out_c: 16.8,
      booster_press_bar: 9.9,
      ejector_press_bar: 10.2,
      strip_steam_pct_of_oil: 1.5,
      strip_steam_flow_kghr: 376.5,
      fp101a_press_bar: 2.3,
      fp101b_press_bar: 2.2,
      remarks: null,
      no_production_reason: null,
      has_deviation: false,
      recorded_by: 'OPR001',
      recorded_by_name: 'Ahmad Razak',
      recorded_at: '2026-09-20T08:04:00+08:00',
    },
    {
      id: 'PL003',
      sheet_id: 'PR001',
      slot_index: 2,
      slot_label: '0900',
      slot_start: '2026-09-20T09:00:00+08:00',
      product_id: DEFAULT_PRODUCT_ID,
      product_name: 'PL 65 Matsuyama',
      oil_feed_rate_litre: 25050,
      deod_time_set_hr: 2.0,
      vacuum_torr: 4.8, // Mild soft deviation (soft max is 4.5)
      tray_1_temp_c: 254.0,
      tray_2_temp_c: 258.1,
      tray_3_temp_c: 262.5,
      tray_4_temp_c: 266.0,
      tray_5_temp_c: 265.2,
      tray_6_temp_c: 243.1,
      tray_7_temp_c: 197.0,
      bc101_water_in_c: 32.1,
      bc101_water_out_c: 44.2,
      chill_water_in_c: 11.0,
      chill_water_out_c: 17.5,
      booster_press_bar: 9.6,
      ejector_press_bar: 9.9,
      strip_steam_pct_of_oil: 1.5,
      strip_steam_flow_kghr: 375.0,
      fp101a_press_bar: 2.4,
      fp101b_press_bar: 2.3,
      remarks: 'Vacuum climbed slightly due to cooling water temp spike. Ejector tuned.',
      no_production_reason: null,
      has_deviation: true,
      recorded_by: 'OPR001',
      recorded_by_name: 'Ahmad Razak',
      recorded_at: '2026-09-20T09:03:00+08:00',
    },
  ],
};

export const INITIAL_DEVIATIONS: Deviation[] = [
  {
    id: 'AR001',
    entry_id: 'PL003',
    slot_label: '0900',
    field_key: 'vacuum_torr',
    field_label: 'Processing Vacuum Reach',
    observed: 4.8,
    soft_min: 1.0,
    soft_max: 4.5,
    acknowledged_by: 'SUP001',
    acknowledged_by_name: 'Chong Wei Lun',
    acknowledged_at: '2026-09-20T09:15:00+08:00',
    action_taken: 'Inspected cooling water tower pump #2 and restored vacuum to 2.8 Torr.',
    created_at: '2026-09-20T09:03:00+08:00',
  }
];

// Sample Reports (RF-FR-001) with Hierarchical UUIDs (70000000-0000-0000-0000-000000000xxx)
export const INITIAL_REPORTS: SampleReport[] = [
  {
    id: 'SR001',
    plant_id: INITIAL_PLANT.id,
    report_no: 'SAR-2026-000481',
    sample_date: '2026-09-20',
    time_check: '07:30',
    lot_no: 'LOT-PL65-2609-01',
    product_id: DEFAULT_PRODUCT_ID,
    product_name: 'PL 65 Matsuyama',
    product_other: null,
    feed_tank_id: DEFAULT_FEED_TANK_ID,
    feed_tank_code: 'TK-101A',
    discharge_tank_id: DEFAULT_DISCHARGE_TANK_ID,
    discharge_tank_code: 'TK-201A',
    crystallizer_no: 'CR-04',
    batch_no: 'B260901',
    sampling_point_id: DEFAULT_SAMPLING_POINT_ID,
    sampling_point_name: 'Deodorizer Outlet Pipe (Header 4)',
    submitted_by: 'OPR001',
    submitted_by_name: 'Ahmad Razak',
    remark_flushing: false,
    remark_cooling: false,
    remark_pushover: false,
    remarks: 'Routine shift startup sample. Process running steady.',
    status: 'decided',
    created_by: 'OPR001',
    created_at: '2026-09-20T07:35:00+08:00',
    results: [
      { id: 'SR001-RES01', report_id: 'SR001', parameter_id: PARAM_IDS.FFA, parameter_code: 'FFA', parameter_name: 'Free Fatty Acid', unit: '%', requested: true, value_numeric: 0.028, in_spec: true },
      { id: 'SR001-RES02', report_id: 'SR001', parameter_id: PARAM_IDS.H2O, parameter_code: 'H2O', parameter_name: 'Moisture & Impurities', unit: '%', requested: true, value_numeric: 0.021, in_spec: true },
      { id: 'SR001-RES03', report_id: 'SR001', parameter_id: PARAM_IDS.IV, parameter_code: 'IV', parameter_name: 'Iodine Value', unit: 'g I₂/100g', requested: true, value_numeric: 65.4, in_spec: true },
      { id: 'SR001-RES04', report_id: 'SR001', parameter_id: PARAM_IDS.PV, parameter_code: 'PV', parameter_name: 'Peroxide Value', unit: 'meq/kg', requested: true, value_numeric: 0.18, in_spec: true },
      { id: 'SR001-RES05', report_id: 'SR001', parameter_id: PARAM_IDS.COLOUR_R, parameter_code: 'COLOUR_R', parameter_name: 'Colour Red', unit: 'R', requested: true, value_numeric: 1.8, in_spec: true },
      { id: 'SR001-RES06', report_id: 'SR001', parameter_id: PARAM_IDS.COLOUR_Y, parameter_code: 'COLOUR_Y', parameter_name: 'Colour Yellow', unit: 'Y', requested: true, value_numeric: 18.0, in_spec: true },
      { id: 'SR001-RES07', report_id: 'SR001', parameter_id: PARAM_IDS.ODOUR, parameter_code: 'ODOUR', parameter_name: 'Odour Assessment', unit: null, requested: true, value_text: 'bland', in_spec: true },
      { id: 'SR001-RES08', report_id: 'SR001', parameter_id: PARAM_IDS.CLOUD_POINT, parameter_code: 'CLOUD_POINT', parameter_name: 'Cloud Point', unit: '°C', requested: true, value_numeric: 2.6, in_spec: true },
      { id: 'SR001-RES09', report_id: 'SR001', parameter_id: PARAM_IDS.TEMP, parameter_code: 'TEMP', parameter_name: 'Temperature 10°C', unit: '-', series_key: 10, requested: true, value_numeric: 51.5, in_spec: true },
      { id: 'SR001-RES10', report_id: 'SR001', parameter_id: PARAM_IDS.TEMP, parameter_code: 'TEMP', parameter_name: 'Temperature 20°C', unit: '-', series_key: 20, requested: true, value_numeric: 26.8, in_spec: true },
      { id: 'SR001-RES11', report_id: 'SR001', parameter_id: PARAM_IDS.TEMP, parameter_code: 'TEMP', parameter_name: 'Temperature 30°C', unit: '-', series_key: 30, requested: true, value_numeric: 7.9, in_spec: true },
      { id: 'SR001-RES12', report_id: 'SR001', parameter_id: PARAM_IDS.TEMP, parameter_code: 'TEMP', parameter_name: 'Temperature 35°C', unit: '-', series_key: 35, requested: true, value_numeric: 0.4, in_spec: true },
    ],
    decision: {
      id: 'QC001',
      report_id: 'SR001',
      decision: 'accept',
      reason_id: null,
      reason_label: null,
      reason_detail: null,
      failed_parameters: [],
      disposition: null,
      decided_by: 'QCS001',
      decided_by_name: 'Siti Nurhaliza',
      decided_at: '2026-09-20T08:15:00+08:00',
    }
  },
  {
    id: 'SR002',
    plant_id: INITIAL_PLANT.id,
    report_no: 'SAR-2026-000482',
    sample_date: '2026-09-20',
    time_check: '09:15',
    lot_no: 'LOT-PL65-2609-02',
    product_id: DEFAULT_PRODUCT_ID,
    product_name: 'PL 65 Matsuyama',
    product_other: null,
    feed_tank_id: 'TK002',
    feed_tank_code: 'TK-101B',
    discharge_tank_id: 'TK005',
    discharge_tank_code: 'TK-201B',
    crystallizer_no: 'CR-04',
    batch_no: 'B260902',
    sampling_point_id: 'SP002',
    sampling_point_name: 'Tray 7 Final Sampling Cock',
    submitted_by: 'OPR001',
    submitted_by_name: 'Ahmad Razak',
    remark_flushing: false,
    remark_cooling: false,
    remark_pushover: false,
    remarks: 'Sample drawn during vacuum excursion at 0900.',
    status: 'decided',
    created_by: 'OPR001',
    created_at: '2026-09-20T09:20:00+08:00',
    results: [
      { id: 'SR002-RES01', report_id: 'SR002', parameter_id: PARAM_IDS.FFA, parameter_code: 'FFA', parameter_name: 'Free Fatty Acid', unit: '%', requested: true, value_numeric: 0.068, in_spec: false },
      { id: 'SR002-RES02', report_id: 'SR002', parameter_id: PARAM_IDS.H2O, parameter_code: 'H2O', parameter_name: 'Moisture & Impurities', unit: '%', requested: true, value_numeric: 0.024, in_spec: true },
      { id: 'SR002-RES03', report_id: 'SR002', parameter_id: PARAM_IDS.IV, parameter_code: 'IV', parameter_name: 'Iodine Value', unit: 'g I₂/100g', requested: true, value_numeric: 65.1, in_spec: true },
      { id: 'SR002-RES04', report_id: 'SR002', parameter_id: PARAM_IDS.PV, parameter_code: 'PV', parameter_name: 'Peroxide Value', unit: 'meq/kg', requested: true, value_numeric: 0.45, in_spec: true },
      { id: 'SR002-RES05', report_id: 'SR002', parameter_id: PARAM_IDS.COLOUR_R, parameter_code: 'COLOUR_R', parameter_name: 'Colour Red', unit: 'R', requested: true, value_numeric: 3.2, in_spec: false },
      { id: 'SR002-RES06', report_id: 'SR002', parameter_id: PARAM_IDS.COLOUR_Y, parameter_code: 'COLOUR_Y', parameter_name: 'Colour Yellow', unit: 'Y', requested: true, value_numeric: 28.0, in_spec: false },
      { id: 'SR002-RES07', report_id: 'SR002', parameter_id: PARAM_IDS.ODOUR, parameter_code: 'ODOUR', parameter_name: 'Odour Assessment', unit: null, requested: true, value_text: 'off', in_spec: false },
    ],
    decision: {
      id: 'QC002',
      report_id: 'SR002',
      decision: 'reject',
      reason_id: 'REJ004',
      reason_label: 'Colour out of specification',
      reason_detail: 'Colour Red 3.2R exceeds 2.5R maximum spec. Noticeable burnt odour due to 0900 vacuum loss.',
      failed_parameters: ['FFA (0.068%)', 'COLOUR_R (3.2R)', 'COLOUR_Y (28.0Y)', 'ODOUR (off)'],
      disposition: 'reprocess',
      decided_by: 'MGR001',
      decided_by_name: 'Dr. Tan Keng Boon',
      decided_at: '2026-09-20T10:15:00+08:00',
    }
  },
  {
    id: 'SR003',
    plant_id: INITIAL_PLANT.id,
    report_no: 'SAR-2026-000483',
    sample_date: '2026-09-20',
    time_check: '11:00',
    lot_no: 'LOT-PL65-2609-03',
    product_id: DEFAULT_PRODUCT_ID,
    product_name: 'PL 65 Matsuyama',
    product_other: null,
    feed_tank_id: DEFAULT_FEED_TANK_ID,
    feed_tank_code: 'TK-101A',
    discharge_tank_id: DEFAULT_DISCHARGE_TANK_ID,
    discharge_tank_code: 'TK-201A',
    crystallizer_no: 'CR-04',
    batch_no: 'B260903',
    sampling_point_id: 'SP003',
    sampling_point_name: 'Cooler BC-101 Discharge Line',
    submitted_by: 'OPR001',
    submitted_by_name: 'Ahmad Razak',
    remark_flushing: false,
    remark_cooling: false,
    remark_pushover: false,
    remarks: 'Post-adjustment verification sample.',
    status: 'awaiting_results',
    created_by: 'OPR001',
    created_at: '2026-09-20T11:05:00+08:00',
    results: [
      { id: 'SR003-RES01', report_id: 'SR003', parameter_id: PARAM_IDS.FFA, parameter_code: 'FFA', parameter_name: 'Free Fatty Acid', unit: '%', requested: true },
      { id: 'SR003-RES02', report_id: 'SR003', parameter_id: PARAM_IDS.H2O, parameter_code: 'H2O', parameter_name: 'Moisture & Impurities', unit: '%', requested: true },
      { id: 'SR003-RES03', report_id: 'SR003', parameter_id: PARAM_IDS.COLOUR_R, parameter_code: 'COLOUR_R', parameter_name: 'Colour Red', unit: 'R', requested: true },
      { id: 'SR003-RES04', report_id: 'SR003', parameter_id: PARAM_IDS.ODOUR, parameter_code: 'ODOUR', parameter_name: 'Odour Assessment', unit: null, requested: true },
    ]
  },
  {
    id: 'SR004',
    plant_id: INITIAL_PLANT.id,
    report_no: 'SAR-2026-000484',
    sample_date: '2026-09-21',
    time_check: '08:00',
    lot_no: 'LOT-CHOCO-2609-01',
    product_id: 'PRD001',
    product_name: 'Chocohi 357A NPHO',
    product_other: null,
    feed_tank_id: 'TK003',
    feed_tank_code: 'TK-102',
    discharge_tank_id: 'TK006',
    discharge_tank_code: 'TK-202',
    crystallizer_no: 'CR-02',
    batch_no: 'B260910',
    sampling_point_id: 'SP004',
    sampling_point_name: 'Polishing Filter FP-101 Manifold',
    submitted_by: 'OPR001',
    submitted_by_name: 'Ahmad Razak',
    remark_flushing: true,
    remark_cooling: false,
    remark_pushover: false,
    remarks: 'Flushing line before batch run.',
    status: 'decided',
    created_by: 'OPR001',
    created_at: '2026-09-21T08:05:00+08:00',
    results: [
      { id: 'SR004-RES01', report_id: 'SR004', parameter_id: PARAM_IDS.FFA, parameter_code: 'FFA', parameter_name: 'Free Fatty Acid', unit: '%', requested: true, value_numeric: 0.035, in_spec: true },
      { id: 'SR004-RES02', report_id: 'SR004', parameter_id: PARAM_IDS.H2O, parameter_code: 'H2O', parameter_name: 'Moisture & Impurities', unit: '%', requested: true, value_numeric: 0.022, in_spec: true },
      { id: 'SR004-RES03', report_id: 'SR004', parameter_id: PARAM_IDS.COLOUR_R, parameter_code: 'COLOUR_R', parameter_name: 'Colour Red', unit: 'R', requested: true, value_numeric: 2.1, in_spec: true },
    ],
    decision: {
      id: 'QC004',
      report_id: 'SR004',
      decision: 'accept',
      reason_id: null,
      reason_label: null,
      reason_detail: null,
      failed_parameters: [],
      disposition: null,
      decided_by: 'MGR001',
      decided_by_name: 'Dr. Tan Keng Boon',
      decided_at: '2026-09-21T08:50:00+08:00',
    }
  },
  {
    id: 'SR005',
    plant_id: INITIAL_PLANT.id,
    report_no: 'SAR-2026-000485',
    sample_date: '2026-09-22',
    time_check: '08:30',
    lot_no: 'LOT-PL65-2609-05',
    product_id: DEFAULT_PRODUCT_ID,
    product_name: 'PL 65 Matsuyama',
    product_other: null,
    feed_tank_id: DEFAULT_FEED_TANK_ID,
    feed_tank_code: 'TK-101A',
    discharge_tank_id: DEFAULT_DISCHARGE_TANK_ID,
    discharge_tank_code: 'TK-201A',
    crystallizer_no: 'CR-04',
    batch_no: 'B260920',
    sampling_point_id: DEFAULT_SAMPLING_POINT_ID,
    sampling_point_name: 'Deodorizer Outlet Pipe (Header 4)',
    submitted_by: 'OPR001',
    submitted_by_name: 'Ahmad Razak',
    remark_flushing: false,
    remark_cooling: true,
    remark_pushover: false,
    remarks: 'Cooling stage check sample.',
    status: 'decided',
    created_by: 'OPR001',
    created_at: '2026-09-22T08:35:00+08:00',
    results: [
      { id: 'SR005-RES01', report_id: 'SR005', parameter_id: PARAM_IDS.FFA, parameter_code: 'FFA', parameter_name: 'Free Fatty Acid', unit: '%', requested: true, value_numeric: 0.029, in_spec: true },
      { id: 'SR005-RES02', report_id: 'SR005', parameter_id: PARAM_IDS.H2O, parameter_code: 'H2O', parameter_name: 'Moisture & Impurities', unit: '%', requested: true, value_numeric: 0.018, in_spec: true },
      { id: 'SR005-RES03', report_id: 'SR005', parameter_id: PARAM_IDS.COLOUR_R, parameter_code: 'COLOUR_R', parameter_name: 'Colour Red', unit: 'R', requested: true, value_numeric: 1.9, in_spec: true },
    ],
    decision: {
      id: 'QC005',
      report_id: 'SR005',
      decision: 'accept',
      reason_id: null,
      reason_label: null,
      reason_detail: null,
      failed_parameters: [],
      disposition: null,
      decided_by: 'QCS001',
      decided_by_name: 'Siti Nurhaliza',
      decided_at: '2026-09-22T09:15:00+08:00',
    }
  },
  {
    id: 'SR006',
    plant_id: INITIAL_PLANT.id,
    report_no: 'SAR-2026-000486',
    sample_date: '2026-09-25',
    time_check: '10:00',
    lot_no: 'LOT-DAISY-2609-01',
    product_id: 'PRD003',
    product_name: 'Daisy Soft PM180602 I2',
    product_other: null,
    feed_tank_id: DEFAULT_FEED_TANK_ID,
    feed_tank_code: 'TK-101A',
    discharge_tank_id: DEFAULT_DISCHARGE_TANK_ID,
    discharge_tank_code: 'TK-201A',
    crystallizer_no: 'CR-03',
    batch_no: 'B260925',
    sampling_point_id: DEFAULT_SAMPLING_POINT_ID,
    sampling_point_name: 'Deodorizer Outlet Pipe (Header 4)',
    submitted_by: 'OPR001',
    submitted_by_name: 'Ahmad Razak',
    remark_flushing: false,
    remark_cooling: false,
    remark_pushover: false,
    remarks: 'Routine cold-stability check for super olein grade.',
    status: 'decided',
    created_by: 'OPR001',
    created_at: '2026-09-25T10:05:00+08:00',
    results: [
      { id: 'SR006-RES01', report_id: 'SR006', parameter_id: PARAM_IDS.FFA, parameter_code: 'FFA', parameter_name: 'Free Fatty Acid', unit: '%', requested: true, value_numeric: 0.024, in_spec: true },
      { id: 'SR006-RES02', report_id: 'SR006', parameter_id: PARAM_IDS.CLOUD_POINT, parameter_code: 'CLOUD_POINT', parameter_name: 'Cloud Point', unit: '°C', requested: true, value_numeric: 6.8, in_spec: false },
      { id: 'SR006-RES03', report_id: 'SR006', parameter_id: PARAM_IDS.COLOUR_R, parameter_code: 'COLOUR_R', parameter_name: 'Colour Red', unit: 'R', requested: true, value_numeric: 2.0, in_spec: true },
    ],
    decision: {
      id: 'QC006',
      report_id: 'SR006',
      decision: 'reject',
      reason_id: 'REJ007',
      reason_label: 'Cloud point out of range',
      reason_detail: 'Cloud point 6.8°C exceeds 5.5°C maximum requirement for Daisy Soft grade. Return to fractionator.',
      failed_parameters: ['CLOUD_POINT (6.8°C)'],
      disposition: 'reprocess',
      decided_by: 'MGR001',
      decided_by_name: 'Dr. Tan Keng Boon',
      decided_at: '2026-09-25T11:00:00+08:00',
    }
  },
  {
    id: 'SR007',
    plant_id: INITIAL_PLANT.id,
    report_no: 'SAR-2026-000487',
    sample_date: '2026-09-28',
    time_check: '14:00',
    lot_no: 'LOT-DAISY-2609-02',
    product_id: 'PRD003',
    product_name: 'Daisy Soft PM180602 I2',
    product_other: null,
    feed_tank_id: DEFAULT_FEED_TANK_ID,
    feed_tank_code: 'TK-101A',
    discharge_tank_id: DEFAULT_DISCHARGE_TANK_ID,
    discharge_tank_code: 'TK-201A',
    crystallizer_no: 'CR-03',
    batch_no: 'B260928',
    sampling_point_id: DEFAULT_SAMPLING_POINT_ID,
    sampling_point_name: 'Deodorizer Outlet Pipe (Header 4)',
    submitted_by: 'OPR001',
    submitted_by_name: 'Ahmad Razak',
    remark_flushing: false,
    remark_cooling: false,
    remark_pushover: false,
    remarks: 'Re-fractionated re-run lot.',
    status: 'decided',
    created_by: 'OPR001',
    created_at: '2026-09-28T14:05:00+08:00',
    results: [
      { id: 'SR007-RES01', report_id: 'SR007', parameter_id: PARAM_IDS.FFA, parameter_code: 'FFA', parameter_name: 'Free Fatty Acid', unit: '%', requested: true, value_numeric: 0.022, in_spec: true },
      { id: 'SR007-RES02', report_id: 'SR007', parameter_id: PARAM_IDS.CLOUD_POINT, parameter_code: 'CLOUD_POINT', parameter_name: 'Cloud Point', unit: '°C', requested: true, value_numeric: 4.8, in_spec: true },
      { id: 'SR007-RES03', report_id: 'SR007', parameter_id: PARAM_IDS.COLOUR_R, parameter_code: 'COLOUR_R', parameter_name: 'Colour Red', unit: 'R', requested: true, value_numeric: 1.7, in_spec: true },
    ],
    decision: {
      id: 'QC007',
      report_id: 'SR007',
      decision: 'accept',
      reason_id: null,
      reason_label: null,
      reason_detail: null,
      failed_parameters: [],
      disposition: null,
      decided_by: 'QCS001',
      decided_by_name: 'Siti Nurhaliza',
      decided_at: '2026-09-28T14:45:00+08:00',
    }
  },
  {
    id: 'SR008',
    plant_id: INITIAL_PLANT.id,
    report_no: 'SAR-2026-000488',
    sample_date: '2026-09-29',
    time_check: '09:00',
    lot_no: 'LOT-NATWOS-2609-01',
    product_id: 'PRD020',
    product_name: 'Naturel WOS',
    product_other: null,
    feed_tank_id: DEFAULT_FEED_TANK_ID,
    feed_tank_code: 'TK-101A',
    discharge_tank_id: DEFAULT_DISCHARGE_TANK_ID,
    discharge_tank_code: 'TK-201A',
    crystallizer_no: 'CR-01',
    batch_no: 'B260929',
    sampling_point_id: DEFAULT_SAMPLING_POINT_ID,
    sampling_point_name: 'Deodorizer Outlet Pipe (Header 4)',
    submitted_by: 'OPR001',
    submitted_by_name: 'Ahmad Razak',
    remark_flushing: false,
    remark_cooling: false,
    remark_pushover: false,
    remarks: 'Premium retail consumer brand run.',
    status: 'decided',
    created_by: 'OPR001',
    created_at: '2026-09-29T09:05:00+08:00',
    results: [
      { id: 'SR008-RES01', report_id: 'SR008', parameter_id: PARAM_IDS.FFA, parameter_code: 'FFA', parameter_name: 'Free Fatty Acid', unit: '%', requested: true, value_numeric: 0.019, in_spec: true },
      { id: 'SR008-RES02', report_id: 'SR008', parameter_id: PARAM_IDS.COLOUR_R, parameter_code: 'COLOUR_R', parameter_name: 'Colour Red', unit: 'R', requested: true, value_numeric: 1.4, in_spec: true },
      { id: 'SR008-RES03', report_id: 'SR008', parameter_id: PARAM_IDS.PV, parameter_code: 'PV', parameter_name: 'Peroxide Value', unit: 'meq/kg', requested: true, value_numeric: 0.12, in_spec: true },
    ],
    decision: {
      id: 'QC008',
      report_id: 'SR008',
      decision: 'accept',
      reason_id: null,
      reason_label: null,
      reason_detail: null,
      failed_parameters: [],
      disposition: null,
      decided_by: 'QCS001',
      decided_by_name: 'Siti Nurhaliza',
      decided_at: '2026-09-29T09:40:00+08:00',
    }
  },
  {
    id: 'SR009',
    plant_id: INITIAL_PLANT.id,
    report_no: 'SAR-2026-000489',
    sample_date: '2026-10-02',
    time_check: '11:00',
    lot_no: 'LOT-RPMO-2610-01',
    product_id: 'PRD031',
    product_name: 'RPMO',
    product_other: null,
    feed_tank_id: DEFAULT_FEED_TANK_ID,
    feed_tank_code: 'TK-101A',
    discharge_tank_id: DEFAULT_DISCHARGE_TANK_ID,
    discharge_tank_code: 'TK-201A',
    crystallizer_no: 'CR-02',
    batch_no: 'B261002',
    sampling_point_id: DEFAULT_SAMPLING_POINT_ID,
    sampling_point_name: 'Deodorizer Outlet Pipe (Header 4)',
    submitted_by: 'OPR001',
    submitted_by_name: 'Ahmad Razak',
    remark_flushing: false,
    remark_cooling: false,
    remark_pushover: false,
    remarks: 'October batch run for Refined Palm Mid Olein.',
    status: 'decided',
    created_by: 'OPR001',
    created_at: '2026-10-02T11:05:00+08:00',
    results: [
      { id: 'SR009-RES01', report_id: 'SR009', parameter_id: PARAM_IDS.FFA, parameter_code: 'FFA', parameter_name: 'Free Fatty Acid', unit: '%', requested: true, value_numeric: 0.058, in_spec: false },
      { id: 'SR009-RES02', report_id: 'SR009', parameter_id: PARAM_IDS.COLOUR_R, parameter_code: 'COLOUR_R', parameter_name: 'Colour Red', unit: 'R', requested: true, value_numeric: 2.3, in_spec: true },
    ],
    decision: {
      id: 'QC009',
      report_id: 'SR009',
      decision: 'reject',
      reason_id: 'REJ001',
      reason_label: 'FFA above specification',
      reason_detail: 'FFA 0.058% exceeds maximum specification limit of 0.050% for RPMO delivery.',
      failed_parameters: ['FFA (0.058%)'],
      disposition: 'downgrade',
      decided_by: 'MGR001',
      decided_by_name: 'Dr. Tan Keng Boon',
      decided_at: '2026-10-02T11:45:00+08:00',
    }
  },
  {
    id: 'SR010',
    plant_id: INITIAL_PLANT.id,
    report_no: 'SAR-2026-000490',
    sample_date: '2026-10-03',
    time_check: '08:30',
    lot_no: 'LOT-RPKO-2610-01',
    product_id: 'PRD039',
    product_name: 'RPKO',
    product_other: null,
    feed_tank_id: 'TK003',
    feed_tank_code: 'TK-102',
    discharge_tank_id: 'TK006',
    discharge_tank_code: 'TK-202',
    crystallizer_no: 'CR-04',
    batch_no: 'B261003',
    sampling_point_id: DEFAULT_SAMPLING_POINT_ID,
    sampling_point_name: 'Deodorizer Outlet Pipe (Header 4)',
    submitted_by: 'OPR001',
    submitted_by_name: 'Ahmad Razak',
    remark_flushing: false,
    remark_cooling: false,
    remark_pushover: false,
    remarks: 'Palm kernel deodorization batch sample.',
    status: 'decided',
    created_by: 'OPR001',
    created_at: '2026-10-03T08:35:00+08:00',
    results: [
      { id: 'SR010-RES01', report_id: 'SR010', parameter_id: PARAM_IDS.FFA, parameter_code: 'FFA', parameter_name: 'Free Fatty Acid', unit: '%', requested: true, value_numeric: 0.042, in_spec: true },
      { id: 'SR010-RES02', report_id: 'SR010', parameter_id: PARAM_IDS.H2O, parameter_code: 'H2O', parameter_name: 'Moisture & Impurities', unit: '%', requested: true, value_numeric: 0.065, in_spec: false },
    ],
    decision: {
      id: 'QC010',
      report_id: 'SR010',
      decision: 'reject',
      reason_id: 'REJ002',
      reason_label: 'Moisture above specification',
      reason_detail: 'Moisture level 0.065% exceeds 0.050% moisture spec. Recirculate through vacuum dryer.',
      failed_parameters: ['H2O (0.065%)'],
      disposition: 'reprocess',
      decided_by: 'MGR001',
      decided_by_name: 'Dr. Tan Keng Boon',
      decided_at: '2026-10-03T09:15:00+08:00',
    }
  },
  {
    id: 'SR011',
    plant_id: INITIAL_PLANT.id,
    report_no: 'SAR-2026-000491',
    sample_date: '2026-10-04',
    time_check: '10:30',
    lot_no: 'LOT-CHOCO-2610-01',
    product_id: 'PRD001',
    product_name: 'Chocohi 357A NPHO',
    product_other: null,
    feed_tank_id: 'TK003',
    feed_tank_code: 'TK-102',
    discharge_tank_id: 'TK006',
    discharge_tank_code: 'TK-202',
    crystallizer_no: 'CR-02',
    batch_no: 'B261011',
    sampling_point_id: DEFAULT_SAMPLING_POINT_ID,
    sampling_point_name: 'Deodorizer Outlet Pipe (Header 4)',
    submitted_by: 'OPR001',
    submitted_by_name: 'Ahmad Razak',
    remark_flushing: false,
    remark_cooling: false,
    remark_pushover: false,
    remarks: 'Specialty chocolate coating fat evaluation.',
    status: 'decided',
    created_by: 'OPR001',
    created_at: '2026-10-04T10:35:00+08:00',
    results: [
      { id: 'SR011-RES01', report_id: 'SR011', parameter_id: PARAM_IDS.FFA, parameter_code: 'FFA', parameter_name: 'Free Fatty Acid', unit: '%', requested: true, value_numeric: 0.038, in_spec: true },
      { id: 'SR011-RES02', report_id: 'SR011', parameter_id: PARAM_IDS.SLIP_MELT, parameter_code: 'SLIP_MELT', parameter_name: 'Slip Melting Point', unit: '°C', requested: true, value_numeric: 38.5, in_spec: false },
    ],
    decision: {
      id: 'QC011',
      report_id: 'SR011',
      decision: 'reject',
      reason_id: 'REJ006',
      reason_label: 'Slip melting point out of range',
      reason_detail: 'Slip melting point 38.5°C exceeds target limit of 37.0°C. Batch requires blending rework.',
      failed_parameters: ['SLIP_MELT (38.5°C)'],
      disposition: 'rework',
      decided_by: 'MGR001',
      decided_by_name: 'Dr. Tan Keng Boon',
      decided_at: '2026-10-04T11:20:00+08:00',
    }
  },
  {
    id: 'SR012',
    plant_id: INITIAL_PLANT.id,
    report_no: 'SAR-2026-000492',
    sample_date: '2026-10-04',
    time_check: '15:00',
    lot_no: 'LOT-NATWOS-2610-01',
    product_id: 'PRD020',
    product_name: 'Naturel WOS',
    product_other: null,
    feed_tank_id: DEFAULT_FEED_TANK_ID,
    feed_tank_code: 'TK-101A',
    discharge_tank_id: DEFAULT_DISCHARGE_TANK_ID,
    discharge_tank_code: 'TK-201A',
    crystallizer_no: 'CR-01',
    batch_no: 'B261014',
    sampling_point_id: DEFAULT_SAMPLING_POINT_ID,
    sampling_point_name: 'Deodorizer Outlet Pipe (Header 4)',
    submitted_by: 'OPR001',
    submitted_by_name: 'Ahmad Razak',
    remark_flushing: false,
    remark_cooling: false,
    remark_pushover: false,
    remarks: 'Mid-shift QA sampling for packaging line.',
    status: 'decided',
    created_by: 'OPR001',
    created_at: '2026-10-04T15:05:00+08:00',
    results: [
      { id: 'SR012-RES01', report_id: 'SR012', parameter_id: PARAM_IDS.FFA, parameter_code: 'FFA', parameter_name: 'Free Fatty Acid', unit: '%', requested: true, value_numeric: 0.021, in_spec: true },
      { id: 'SR012-RES02', report_id: 'SR012', parameter_id: PARAM_IDS.PV, parameter_code: 'PV', parameter_name: 'Peroxide Value', unit: 'meq/kg', requested: true, value_numeric: 0.32, in_spec: false },
    ],
    decision: {
      id: 'QC012',
      report_id: 'SR012',
      decision: 'accept_concession',
      reason_id: 'REJ003',
      reason_label: 'Peroxide value above specification',
      reason_detail: 'PV 0.32 meq/kg slightly over target 0.25 meq/kg but within acceptable food safety threshold. Approved under QA concession.',
      failed_parameters: ['PV (0.32 meq/kg)'],
      disposition: 'hold',
      decided_by: 'MGR001',
      decided_by_name: 'Dr. Tan Keng Boon',
      decided_at: '2026-10-04T15:40:00+08:00',
    }
  },
  {
    id: 'SR013',
    plant_id: INITIAL_PLANT.id,
    report_no: 'SAR-2026-000493',
    sample_date: '2026-10-05',
    time_check: '08:00',
    lot_no: 'LOT-PL65-2610-01',
    product_id: DEFAULT_PRODUCT_ID,
    product_name: 'PL 65 Matsuyama',
    product_other: null,
    feed_tank_id: DEFAULT_FEED_TANK_ID,
    feed_tank_code: 'TK-101A',
    discharge_tank_id: DEFAULT_DISCHARGE_TANK_ID,
    discharge_tank_code: 'TK-201A',
    crystallizer_no: 'CR-04',
    batch_no: 'B261005',
    sampling_point_id: DEFAULT_SAMPLING_POINT_ID,
    sampling_point_name: 'Deodorizer Outlet Pipe (Header 4)',
    submitted_by: 'OPR001',
    submitted_by_name: 'Ahmad Razak',
    remark_flushing: false,
    remark_cooling: false,
    remark_pushover: false,
    remarks: 'Live shift startup batch.',
    status: 'decided',
    created_by: 'OPR001',
    created_at: '2026-10-05T08:05:00+08:00',
    results: [
      { id: 'SR013-RES01', report_id: 'SR013', parameter_id: PARAM_IDS.FFA, parameter_code: 'FFA', parameter_name: 'Free Fatty Acid', unit: '%', requested: true, value_numeric: 0.027, in_spec: true },
      { id: 'SR013-RES02', report_id: 'SR013', parameter_id: PARAM_IDS.COLOUR_R, parameter_code: 'COLOUR_R', parameter_name: 'Colour Red', unit: 'R', requested: true, value_numeric: 1.8, in_spec: true },
    ],
    decision: {
      id: 'QC013',
      report_id: 'SR013',
      decision: 'accept',
      reason_id: null,
      reason_label: null,
      reason_detail: null,
      failed_parameters: [],
      disposition: null,
      decided_by: 'QCS001',
      decided_by_name: 'Siti Nurhaliza',
      decided_at: '2026-10-05T08:45:00+08:00',
    }
  },
  {
    id: 'SR014',
    plant_id: INITIAL_PLANT.id,
    report_no: 'SAR-2026-000494',
    sample_date: '2026-10-05',
    time_check: '12:00',
    lot_no: 'LOT-PFAD-2610-01',
    product_id: 'PRD045',
    product_name: 'PFAD',
    product_other: null,
    feed_tank_id: DEFAULT_FEED_TANK_ID,
    feed_tank_code: 'TK-101A',
    discharge_tank_id: DEFAULT_DISCHARGE_TANK_ID,
    discharge_tank_code: 'TK-201A',
    crystallizer_no: 'CR-04',
    batch_no: 'B261005P',
    sampling_point_id: DEFAULT_SAMPLING_POINT_ID,
    sampling_point_name: 'PFAD Catch Tank TK-301',
    submitted_by: 'OPR001',
    submitted_by_name: 'Ahmad Razak',
    remark_flushing: false,
    remark_cooling: false,
    remark_pushover: false,
    remarks: 'Distillate fatty acid quality check.',
    status: 'decided',
    created_by: 'OPR001',
    created_at: '2026-10-05T12:05:00+08:00',
    results: [
      { id: 'SR014-RES01', report_id: 'SR014', parameter_id: PARAM_IDS.FFA, parameter_code: 'FFA', parameter_name: 'Free Fatty Acid', unit: '%', requested: true, value_numeric: 88.5, in_spec: true },
      { id: 'SR014-RES02', report_id: 'SR014', parameter_id: PARAM_IDS.H2O, parameter_code: 'H2O', parameter_name: 'Moisture & Impurities', unit: '%', requested: true, value_numeric: 0.45, in_spec: true },
    ],
    decision: {
      id: 'QC014',
      report_id: 'SR014',
      decision: 'accept',
      reason_id: null,
      reason_label: null,
      reason_detail: null,
      failed_parameters: [],
      disposition: null,
      decided_by: 'QCS001',
      decided_by_name: 'Siti Nurhaliza',
      decided_at: '2026-10-05T12:40:00+08:00',
    }
  }
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'AL001',
    table_name: 'process_sheets',
    record_id: 'PR001',
    action: 'insert',
    actor_name: 'Ahmad Razak (Lead Operator)',
    new_row: { shift_date: '2026-09-20', stripping_steam_pct: 1.5, set_steam_supply_bar: 3.0, status: 'open' },
    occurred_at: '2026-09-20T06:55:00+08:00',
  },
  {
    id: 'AL002',
    table_name: 'process_entries',
    record_id: 'PL003',
    action: 'insert',
    actor_name: 'Ahmad Razak (Lead Operator)',
    new_row: { slot_label: '0900', vacuum_torr: 4.8, has_deviation: true },
    occurred_at: '2026-09-20T09:03:00+08:00',
  },
  {
    id: 'AL003',
    table_name: 'qc_decisions',
    record_id: 'QC002',
    action: 'insert',
    actor_name: 'Dr. Tan Keng Boon (QC Manager)',
    new_row: { decision: 'reject', reason: 'Colour out of specification', disposition: 'reprocess' },
    occurred_at: '2026-09-20T10:15:00+08:00',
  },
  {
    id: 'AL004',
    table_name: 'sample_reports',
    record_id: 'SR001',
    action: 'insert',
    actor_name: 'Ahmad Razak (Lead Operator)',
    new_row: { report_no: 'SAR-2026-000481', lot_no: 'LOT-PL65-2609-01', status: 'decided' },
    occurred_at: '2026-09-20T07:35:00+08:00',
  }
];
