// ==============================================================================
// REFINERY PROCESS MANAGEMENT SYSTEM (PRD-REF-001)
// Authentic Industrial Seed & Mock Data: Nisshin Deodorizer Plant & Lab
// ==============================================================================

import { 
  Plant, 
  Profile, 
  Product, 
  Tank, 
  SamplingPoint, 
  Parameter, 
  ParameterLimit, 
  ProductSpec, 
  ProcessSheet, 
  SampleReport, 
  Deviation,
  RejectionReason,
  AuditLogEntry
} from '@/types/refinery';

export const INITIAL_PLANT: Plant = {
  id: '11111111-1111-1111-1111-111111111111',
  code: 'NISSHIN_DEOD',
  name: 'Nisshin Deodorizer Plant',
  timezone: 'Asia/Kuala_Lumpur',
  active: true,
};

export const INITIAL_PROFILES: Profile[] = [
  {
    id: 'OP-1042',
    employee_no: 'OP-1042',
    full_name: 'Ahmad Razak (Lead Operator)',
    role: 'operator',
    status: 'active',
    active: true,
    password: 'password123',
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'SV-2014',
    employee_no: 'SV-2014',
    full_name: 'Chong Wei Lun (Shift Supervisor)',
    role: 'supervisor',
    status: 'active',
    active: true,
    password: 'password123',
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'QC-3201',
    employee_no: 'QC-3201',
    full_name: 'Siti Nurhaliza (QC Lab Analyst)',
    role: 'qc_analyst',
    status: 'active',
    active: true,
    password: 'password123',
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'QM-4502',
    employee_no: 'QM-4502',
    full_name: 'Dr. Tan Keng Boon (QC Manager)',
    role: 'qc_manager',
    status: 'active',
    active: true,
    password: 'password123',
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'AD-5010',
    employee_no: 'AD-5010',
    full_name: 'Haris Iskandar (Plant Administrator)',
    role: 'admin',
    status: 'active',
    active: true,
    password: 'password123',
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'AU-9901',
    employee_no: 'AU-9901',
    full_name: 'ISO Quality Auditor (Viewer)',
    role: 'viewer',
    status: 'active',
    active: true,
    password: 'password123',
    created_at: '2026-01-10T00:00:00Z',
  },
];

// All 44 Products from Appendix 18
export const INITIAL_PRODUCTS: Product[] = [
  { id: 'prod-01', code: 'CHOCOHI_357A_NPHO', name: 'Chocohi 357A NPHO', category: 'specialty', sort_order: 1, active: true },
  { id: 'prod-02', code: 'CHOCOHI_369A', name: 'Chocohi 369A', category: 'specialty', sort_order: 2, active: true },
  { id: 'prod-03', code: 'DAISY_SOFT_PM180602_I2', name: 'Daisy Soft PM180602 I2', category: 'olein', sort_order: 3, active: true },
  { id: 'prod-04', code: 'DF_20', name: 'DF 20', category: 'blend', sort_order: 4, active: true },
  { id: 'prod-05', code: 'FARM_COW_R2', name: 'Farm Cow R2', category: 'blend', sort_order: 5, active: true },
  { id: 'prod-06', code: 'G9', name: 'G9', category: 'blend', sort_order: 6, active: true },
  { id: 'prod-07', code: 'HPO_58', name: 'HPO 58', category: 'stearin', sort_order: 7, active: true },
  { id: 'prod-08', code: 'HPKO', name: 'HPKO', category: 'kernel', sort_order: 8, active: true },
  { id: 'prod-09', code: 'HPS_52', name: 'HPS 52', category: 'stearin', sort_order: 9, active: true },
  { id: 'prod-10', code: 'HPS_58', name: 'HPS 58', category: 'stearin', sort_order: 10, active: true },
  { id: 'prod-11', code: 'HYFAT_L1', name: 'Hyfat L1', category: 'specialty', sort_order: 11, active: true },
  { id: 'prod-12', code: 'HYFAT_K1_P', name: 'Hyfat K1 (P)', category: 'specialty', sort_order: 12, active: true },
  { id: 'prod-13', code: 'HYFAT_K1_B', name: 'Hyfat K1 (B)', category: 'specialty', sort_order: 13, active: true },
  { id: 'prod-14', code: 'PMF', name: 'PMF', category: 'specialty', sort_order: 14, active: true },
  { id: 'prod-15', code: 'PR_PMF', name: 'PR PMF', category: 'specialty', sort_order: 15, active: true },
  { id: 'prod-16', code: 'IEPMF', name: 'IEPMF', category: 'specialty', sort_order: 16, active: true },
  { id: 'prod-17', code: 'R_IEPMF', name: 'R. IEPMF', category: 'specialty', sort_order: 17, active: true },
  { id: 'prod-18', code: 'PR_IEPMF', name: 'PR IEPMF', category: 'specialty', sort_order: 18, active: true },
  { id: 'prod-19', code: 'KRIMWELL_IER', name: 'Krimwell IER', category: 'specialty', sort_order: 19, active: true },
  { id: 'prod-20', code: 'NATUREL_WOS', name: 'Naturel WOS', category: 'consumer', sort_order: 20, active: true },
  { id: 'prod-21', code: 'NATUREL_LITE', name: 'Naturel Lite', category: 'consumer', sort_order: 21, active: true },
  { id: 'prod-22', code: 'NATUREL_OLIVE', name: 'Naturel Olive', category: 'consumer', sort_order: 22, active: true },
  { id: 'prod-23', code: 'PASTRIFET_SK', name: 'Pastrifet SK', category: 'shortening', sort_order: 23, active: true },
  { id: 'prod-24', code: 'PL_56', name: 'PL 56', category: 'olein', sort_order: 24, active: true },
  { id: 'prod-25', code: 'PL_60', name: 'PL 60', category: 'olein', sort_order: 25, active: true },
  { id: 'prod-26', code: 'PL_65_MATSUYAMA', name: 'PL 65 Matsuyama', category: 'olein', sort_order: 26, active: true },
  { id: 'prod-27', code: 'PL_65_WAYIDEAL', name: 'PL 65 Wayideal', category: 'olein', sort_order: 27, active: true },
  { id: 'prod-28', code: 'PR_PL65', name: 'PR PL65', category: 'olein', sort_order: 28, active: true },
  { id: 'prod-29', code: 'NBD_PL65', name: 'NBD PL65', category: 'olein', sort_order: 29, active: true },
  { id: 'prod-30', code: 'PALM_FAT_BLEND', name: 'Palm Fat Blend', category: 'blend', sort_order: 30, active: true },
  { id: 'prod-31', code: 'RPMO', name: 'RPMO', category: 'olein', sort_order: 31, active: true },
  { id: 'prod-32', code: 'PR_PMO', name: 'PR PMO', category: 'olein', sort_order: 32, active: true },
  { id: 'prod-33', code: 'RSTN', name: 'RSTN', category: 'stearin', sort_order: 33, active: true },
  { id: 'prod-34', code: 'RSTN_S', name: 'RSTN (S)', category: 'stearin', sort_order: 34, active: true },
  { id: 'prod-35', code: 'RSTN_H', name: 'RSTN (H)', category: 'stearin', sort_order: 35, active: true },
  { id: 'prod-36', code: 'PR_STN', name: 'PR STN', category: 'stearin', sort_order: 36, active: true },
  { id: 'prod-37', code: 'PR_STN_S', name: 'PR STN (S)', category: 'stearin', sort_order: 37, active: true },
  { id: 'prod-38', code: 'PR_STN_H', name: 'PR STN (H)', category: 'stearin', sort_order: 38, active: true },
  { id: 'prod-39', code: 'RPKO', name: 'RPKO', category: 'kernel', sort_order: 39, active: true },
  { id: 'prod-40', code: 'RPKL', name: 'RPKL', category: 'kernel', sort_order: 40, active: true },
  { id: 'prod-41', code: 'SHORTENING', name: 'Shortening', category: 'shortening', sort_order: 41, active: true },
  { id: 'prod-42', code: 'SRIV60_FMF_SNAX', name: 'SRIV60 (FMF Snax)', category: 'specialty', sort_order: 42, active: true },
  { id: 'prod-43', code: 'SPLASH_OIL', name: 'Splash Oil', category: 'blend', sort_order: 43, active: true },
  { id: 'prod-44', code: 'FLUSH_OIL', name: 'Flush Oil', category: 'by-product', sort_order: 44, active: true },
  { id: 'prod-45', code: 'PFAD', name: 'PFAD', category: 'by-product', sort_order: 45, active: true },
];

export const INITIAL_TANKS: Tank[] = [
  { id: 'tank-01', plant_id: INITIAL_PLANT.id, code: 'TK-101A', kind: 'feed', active: true },
  { id: 'tank-02', plant_id: INITIAL_PLANT.id, code: 'TK-101B', kind: 'feed', active: true },
  { id: 'tank-03', plant_id: INITIAL_PLANT.id, code: 'TK-102', kind: 'feed', active: true },
  { id: 'tank-04', plant_id: INITIAL_PLANT.id, code: 'TK-201A', kind: 'discharge', active: true },
  { id: 'tank-05', plant_id: INITIAL_PLANT.id, code: 'TK-201B', kind: 'discharge', active: true },
  { id: 'tank-06', plant_id: INITIAL_PLANT.id, code: 'TK-202', kind: 'discharge', active: true },
];

export const INITIAL_SAMPLING_POINTS: SamplingPoint[] = [
  { id: 'sp-01', plant_id: INITIAL_PLANT.id, name: 'Deodorizer Outlet Pipe (Header 4)', active: true },
  { id: 'sp-02', plant_id: INITIAL_PLANT.id, name: 'Tray 7 Final Sampling Cock', active: true },
  { id: 'sp-03', plant_id: INITIAL_PLANT.id, name: 'Cooler BC-101 Discharge Line', active: true },
  { id: 'sp-04', plant_id: INITIAL_PLANT.id, name: 'Polishing Filter FP-101 Manifold', active: true },
  { id: 'sp-05', plant_id: INITIAL_PLANT.id, name: 'Finished Oil Storage Inflow', active: true },
];

export const INITIAL_PARAMETERS: Parameter[] = [
  { id: 'param-ffa', code: 'FFA', name: 'Free Fatty Acid (Palmitic)', unit: '%', decimals: 2, is_series: false, input_kind: 'numeric', sort_order: 1 },
  { id: 'param-h2o', code: 'H2O', name: 'Moisture & Impurities', unit: '%', decimals: 3, is_series: false, input_kind: 'numeric', sort_order: 2 },
  { id: 'param-iv', code: 'IV', name: 'Iodine Value (Wijs)', unit: 'g I₂/100g', decimals: 1, is_series: false, input_kind: 'numeric', sort_order: 3 },
  { id: 'param-pv', code: 'PV', name: 'Peroxide Value', unit: 'meq/kg', decimals: 2, is_series: false, input_kind: 'numeric', sort_order: 4 },
  { id: 'param-col-r', code: 'COLOUR_R', name: 'Colour Lovibond Red (5¼" cell)', unit: 'R', decimals: 1, is_series: false, input_kind: 'numeric', sort_order: 5 },
  { id: 'param-col-y', code: 'COLOUR_Y', name: 'Colour Lovibond Yellow (5¼" cell)', unit: 'Y', decimals: 1, is_series: false, input_kind: 'numeric', sort_order: 6 },
  { id: 'param-odour', code: 'ODOUR', name: 'Odour Assessment', unit: null, decimals: 0, is_series: false, input_kind: 'select', sort_order: 7 },
  { id: 'param-bpp', code: 'BPP', name: 'Breakdown Product Point', unit: '°C', decimals: 1, is_series: false, input_kind: 'numeric', sort_order: 8 },
  { id: 'param-smp', code: 'SLIP_MELT', name: 'Slip Melting Point', unit: '°C', decimals: 1, is_series: false, input_kind: 'numeric', sort_order: 9 },
  { id: 'param-cloud', code: 'CLOUD_POINT', name: 'Cloud Point', unit: '°C', decimals: 1, is_series: false, input_kind: 'numeric', sort_order: 10 },
  { id: 'param-soap', code: 'SOAP', name: 'Soap Content', unit: 'ppm', decimals: 1, is_series: false, input_kind: 'numeric', sort_order: 11 },
  { id: 'param-fac', code: 'FAC_C12', name: 'Fatty Acid Composition C12:0', unit: '%', decimals: 2, is_series: false, input_kind: 'numeric', sort_order: 12 },
  { id: 'param-sfc', code: 'SFC', name: 'Solid Fat Content Series', unit: '%', decimals: 1, is_series: true, series_values: [10, 15, 20, 25, 30, 35, 40, 45, 50], input_kind: 'numeric', sort_order: 13 },
];

export const INITIAL_LIMITS: ParameterLimit[] = [
  { id: 'lim-vac', plant_id: INITIAL_PLANT.id, field_key: 'vacuum_torr', hard_min: 0, hard_max: 760, soft_min: 1.0, soft_max: 4.5 },
  { id: 'lim-t1', plant_id: INITIAL_PLANT.id, field_key: 'tray_1_temp_c', hard_min: 0, hard_max: 350, soft_min: 240, soft_max: 260 },
  { id: 'lim-t2', plant_id: INITIAL_PLANT.id, field_key: 'tray_2_temp_c', hard_min: 0, hard_max: 350, soft_min: 245, soft_max: 262 },
  { id: 'lim-t3', plant_id: INITIAL_PLANT.id, field_key: 'tray_3_temp_c', hard_min: 0, hard_max: 350, soft_min: 248, soft_max: 265 },
  { id: 'lim-t4', plant_id: INITIAL_PLANT.id, field_key: 'tray_4_temp_c', hard_min: 0, hard_max: 350, soft_min: 250, soft_max: 268 },
  { id: 'lim-t5', plant_id: INITIAL_PLANT.id, field_key: 'tray_5_temp_c', hard_min: 0, hard_max: 350, soft_min: 250, soft_max: 268 },
  { id: 'lim-t6', plant_id: INITIAL_PLANT.id, field_key: 'tray_6_temp_c', hard_min: 0, hard_max: 350, soft_min: 235, soft_max: 250 },
  { id: 'lim-t7', plant_id: INITIAL_PLANT.id, field_key: 'tray_7_temp_c', hard_min: 0, hard_max: 350, soft_min: 180, soft_max: 210 },
  { id: 'lim-bc-in', plant_id: INITIAL_PLANT.id, field_key: 'bc101_water_in_c', hard_min: 0, hard_max: 150, soft_min: 28, soft_max: 34 },
  { id: 'lim-bc-out', plant_id: INITIAL_PLANT.id, field_key: 'bc101_water_out_c', hard_min: 0, hard_max: 150, soft_min: 36, soft_max: 48 },
  { id: 'lim-ch-in', plant_id: INITIAL_PLANT.id, field_key: 'chill_water_in_c', hard_min: 0, hard_max: 100, soft_min: 8, soft_max: 14 },
  { id: 'lim-ch-out', plant_id: INITIAL_PLANT.id, field_key: 'chill_water_out_c', hard_min: 0, hard_max: 100, soft_min: 14, soft_max: 22 },
  { id: 'lim-boost', plant_id: INITIAL_PLANT.id, field_key: 'booster_press_bar', hard_min: 0, hard_max: 60, soft_min: 8.0, soft_max: 12.0 },
  { id: 'lim-ejec', plant_id: INITIAL_PLANT.id, field_key: 'ejector_press_bar', hard_min: 0, hard_max: 60, soft_min: 8.0, soft_max: 12.0 },
  { id: 'lim-st-pct', plant_id: INITIAL_PLANT.id, field_key: 'strip_steam_pct_of_oil', hard_min: 0, hard_max: 100, soft_min: 1.2, soft_max: 1.8 },
  { id: 'lim-fp-a', plant_id: INITIAL_PLANT.id, field_key: 'fp101a_press_bar', hard_min: 0, hard_max: 20, soft_min: 1.5, soft_max: 4.5 },
  { id: 'lim-fp-b', plant_id: INITIAL_PLANT.id, field_key: 'fp101b_press_bar', hard_min: 0, hard_max: 20, soft_min: 1.5, soft_max: 4.5 },
];

export const INITIAL_REJECTION_REASONS: RejectionReason[] = [
  { id: 'rej-01', code: 'FFA_HIGH', label: 'FFA above specification', active: true },
  { id: 'rej-02', code: 'H2O_HIGH', label: 'Moisture above specification', active: true },
  { id: 'rej-03', code: 'PV_HIGH', label: 'Peroxide value above specification', active: true },
  { id: 'rej-04', code: 'COLOUR_OUT', label: 'Colour out of specification', active: true },
  { id: 'rej-05', code: 'OFF_ODOUR', label: 'Off odour detected', active: true },
  { id: 'rej-06', code: 'SMP_OUT', label: 'Slip melting point out of range', active: true },
  { id: 'rej-07', code: 'CLOUD_OUT', label: 'Cloud point out of range', active: true },
  { id: 'rej-08', code: 'SFC_OUT', label: 'SFC profile out of range', active: true },
  { id: 'rej-09', code: 'SOAP_HIGH', label: 'Soap content above limit', active: true },
  { id: 'rej-10', code: 'IV_OUT', label: 'Iodine value out of range', active: true },
  { id: 'rej-11', code: 'CONTAMINATION', label: 'Cross-contamination suspected', active: true },
  { id: 'rej-12', code: 'WRONG_TANK', label: 'Wrong product in tank', active: true },
  { id: 'rej-13', code: 'SAMPLING_ERR', label: 'Sampling error, resample required', active: true },
];

// Product specifications for PL 65 Matsuyama (Product 26)
export const INITIAL_SPECS: ProductSpec[] = [
  { id: 'spec-01', product_id: 'prod-26', parameter_id: 'param-ffa', max_value: 0.05, target_value: 0.03, effective_from: '2026-01-01' },
  { id: 'spec-02', product_id: 'prod-26', parameter_id: 'param-h2o', max_value: 0.050, target_value: 0.025, effective_from: '2026-01-01' },
  { id: 'spec-03', product_id: 'prod-26', parameter_id: 'param-iv', min_value: 64.0, max_value: 67.0, target_value: 65.2, effective_from: '2026-01-01' },
  { id: 'spec-04', product_id: 'prod-26', parameter_id: 'param-pv', max_value: 1.00, target_value: 0.20, effective_from: '2026-01-01' },
  { id: 'spec-05', product_id: 'prod-26', parameter_id: 'param-col-r', max_value: 2.5, target_value: 2.0, effective_from: '2026-01-01' },
  { id: 'spec-06', product_id: 'prod-26', parameter_id: 'param-col-y', max_value: 25.0, target_value: 20.0, effective_from: '2026-01-01' },
  { id: 'spec-07', product_id: 'prod-26', parameter_id: 'param-cloud', max_value: 3.5, target_value: 2.8, effective_from: '2026-01-01' },
  // SFC specs
  { id: 'spec-sfc-10', product_id: 'prod-26', parameter_id: 'param-sfc', series_key: 10, min_value: 48.0, max_value: 56.0, target_value: 52.0, effective_from: '2026-01-01' },
  { id: 'spec-sfc-20', product_id: 'prod-26', parameter_id: 'param-sfc', series_key: 20, min_value: 24.0, max_value: 30.0, target_value: 27.0, effective_from: '2026-01-01' },
  { id: 'spec-sfc-30', product_id: 'prod-26', parameter_id: 'param-sfc', series_key: 30, min_value: 6.0, max_value: 10.0, target_value: 8.0, effective_from: '2026-01-01' },
  { id: 'spec-sfc-35', product_id: 'prod-26', parameter_id: 'param-sfc', series_key: 35, max_value: 2.0, target_value: 0.5, effective_from: '2026-01-01' },
];

// 24-Hour Process Sheet for Today
export const INITIAL_SHEET: ProcessSheet = {
  id: 'sheet-today-001',
  plant_id: INITIAL_PLANT.id,
  shift_date: '2026-09-20',
  stripping_steam_pct: 1.5,
  set_steam_supply_bar: 3.0,
  status: 'open',
  opened_by: 'p-op-01',
  opened_by_name: 'Ahmad Razak',
  opened_at: '2026-09-20T06:55:00+08:00',
  verified_by: null,
  verified_at: null,
  entries: [
    {
      id: 'entry-00',
      sheet_id: 'sheet-today-001',
      slot_index: 0,
      slot_label: '0700',
      slot_start: '2026-09-20T07:00:00+08:00',
      product_id: 'prod-26',
      product_name: 'PL 65 Matsuyama',
      oil_feed_rate_litre: 25000,
      deod_time_set_hr: 2.0,
      vacuum_torr: 2.4,
      tray_1_temp_c: 252.0,
      tray_2_temp_c: 256.4,
      tray_3_temp_c: 260.1,
      tray_4_temp_c: 264.5,
      tray_5_temp_c: 263.8,
      tray_6_temp_c: 242.0,
      tray_7_temp_c: 195.0,
      bc101_water_in_c: 30.5,
      bc101_water_out_c: 42.0,
      chill_water_in_c: 10.2,
      chill_water_out_c: 16.5,
      booster_press_bar: 9.8,
      ejector_press_bar: 10.1,
      strip_steam_pct_of_oil: 1.5,
      strip_steam_flow_kghr: 375.0,
      fp101a_press_bar: 2.2,
      fp101b_press_bar: 2.1,
      remarks: 'Start of shift. Plant running steady on PL 65.',
      no_production_reason: null,
      has_deviation: false,
      recorded_by: 'p-op-01',
      recorded_by_name: 'Ahmad Razak',
      recorded_at: '2026-09-20T07:05:00+08:00',
    },
    {
      id: 'entry-01',
      sheet_id: 'sheet-today-001',
      slot_index: 1,
      slot_label: '0800',
      slot_start: '2026-09-20T08:00:00+08:00',
      product_id: 'prod-26',
      product_name: 'PL 65 Matsuyama',
      oil_feed_rate_litre: 25100,
      deod_time_set_hr: 2.0,
      vacuum_torr: 2.5,
      tray_1_temp_c: 253.2,
      tray_2_temp_c: 257.0,
      tray_3_temp_c: 261.2,
      tray_4_temp_c: 265.1,
      tray_5_temp_c: 264.0,
      tray_6_temp_c: 242.5,
      tray_7_temp_c: 196.2,
      bc101_water_in_c: 31.0,
      bc101_water_out_c: 42.5,
      chill_water_in_c: 10.4,
      chill_water_out_c: 16.8,
      booster_press_bar: 9.9,
      ejector_press_bar: 10.2,
      strip_steam_pct_of_oil: 1.5,
      strip_steam_flow_kghr: 376.5,
      fp101a_press_bar: 2.3,
      fp101b_press_bar: 2.2,
      remarks: null,
      no_production_reason: null,
      has_deviation: false,
      recorded_by: 'p-op-01',
      recorded_by_name: 'Ahmad Razak',
      recorded_at: '2026-09-20T08:04:00+08:00',
    },
    {
      id: 'entry-02',
      sheet_id: 'sheet-today-001',
      slot_index: 2,
      slot_label: '0900',
      slot_start: '2026-09-20T09:00:00+08:00',
      product_id: 'prod-26',
      product_name: 'PL 65 Matsuyama',
      oil_feed_rate_litre: 25050,
      deod_time_set_hr: 2.0,
      vacuum_torr: 4.8, // Mild soft deviation (soft max is 4.5)
      tray_1_temp_c: 254.0,
      tray_2_temp_c: 258.1,
      tray_3_temp_c: 262.5,
      tray_4_temp_c: 266.0,
      tray_5_temp_c: 265.2,
      tray_6_temp_c: 243.1,
      tray_7_temp_c: 197.0,
      bc101_water_in_c: 32.1,
      bc101_water_out_c: 44.2,
      chill_water_in_c: 11.0,
      chill_water_out_c: 17.5,
      booster_press_bar: 9.6,
      ejector_press_bar: 9.9,
      strip_steam_pct_of_oil: 1.5,
      strip_steam_flow_kghr: 375.0,
      fp101a_press_bar: 2.4,
      fp101b_press_bar: 2.3,
      remarks: 'Vacuum climbed slightly due to cooling water temp spike. Ejector tuned.',
      no_production_reason: null,
      has_deviation: true,
      recorded_by: 'p-op-01',
      recorded_by_name: 'Ahmad Razak',
      recorded_at: '2026-09-20T09:03:00+08:00',
    },
  ],
};

export const INITIAL_DEVIATIONS: Deviation[] = [
  {
    id: 'dev-001',
    entry_id: 'entry-02',
    slot_label: '0900',
    field_key: 'vacuum_torr',
    field_label: 'Processing Vacuum Reach',
    observed: 4.8,
    soft_min: 1.0,
    soft_max: 4.5,
    acknowledged_by: 'p-sup-01',
    acknowledged_by_name: 'Chong Wei Lun',
    acknowledged_at: '2026-09-20T09:15:00+08:00',
    action_taken: 'Inspected cooling water tower pump #2 and restored vacuum to 2.8 Torr.',
    created_at: '2026-09-20T09:03:00+08:00',
  }
];

// Sample Reports (RF-FR-001)
export const INITIAL_REPORTS: SampleReport[] = [
  {
    id: 'rep-001',
    plant_id: INITIAL_PLANT.id,
    report_no: 'SAR-2026-000481',
    sample_date: '2026-09-20',
    time_check: '07:30',
    lot_no: 'LOT-PL65-2609-01',
    product_id: 'prod-26',
    product_name: 'PL 65 Matsuyama',
    product_other: null,
    feed_tank_id: 'tank-01',
    feed_tank_code: 'TK-101A',
    discharge_tank_id: 'tank-04',
    discharge_tank_code: 'TK-201A',
    crystallizer_no: 'CR-04',
    batch_no: 'B260901',
    sampling_point_id: 'sp-01',
    sampling_point_name: 'Deodorizer Outlet Pipe (Header 4)',
    submitted_by: 'p-op-01',
    submitted_by_name: 'Ahmad Razak',
    remark_flushing: false,
    remark_cooling: false,
    remark_pushover: false,
    remarks: 'Routine hourly composite sample.',
    status: 'decided',
    created_by: 'p-op-01',
    created_at: '2026-09-20T07:35:00+08:00',
    results: [
      { id: 'res-1', report_id: 'rep-001', parameter_id: 'param-ffa', parameter_code: 'FFA', parameter_name: 'Free Fatty Acid', unit: '%', requested: true, value_numeric: 0.028, in_spec: true },
      { id: 'res-2', report_id: 'rep-001', parameter_id: 'param-h2o', parameter_code: 'H2O', parameter_name: 'Moisture & Impurities', unit: '%', requested: true, value_numeric: 0.021, in_spec: true },
      { id: 'res-3', report_id: 'rep-001', parameter_id: 'param-iv', parameter_code: 'IV', parameter_name: 'Iodine Value', unit: 'g I₂/100g', requested: true, value_numeric: 65.4, in_spec: true },
      { id: 'res-4', report_id: 'rep-001', parameter_id: 'param-pv', parameter_code: 'PV', parameter_name: 'Peroxide Value', unit: 'meq/kg', requested: true, value_numeric: 0.18, in_spec: true },
      { id: 'res-5', report_id: 'rep-001', parameter_id: 'param-col-r', parameter_code: 'COLOUR_R', parameter_name: 'Colour Red', unit: 'R', requested: true, value_numeric: 1.8, in_spec: true },
      { id: 'res-6', report_id: 'rep-001', parameter_id: 'param-col-y', parameter_code: 'COLOUR_Y', parameter_name: 'Colour Yellow', unit: 'Y', requested: true, value_numeric: 18.0, in_spec: true },
      { id: 'res-7', report_id: 'rep-001', parameter_id: 'param-odour', parameter_code: 'ODOUR', parameter_name: 'Odour Assessment', unit: null, requested: true, value_text: 'bland', in_spec: true },
      { id: 'res-8', report_id: 'rep-001', parameter_id: 'param-cloud', parameter_code: 'CLOUD_POINT', parameter_name: 'Cloud Point', unit: '°C', requested: true, value_numeric: 2.6, in_spec: true },
      // SFC series
      { id: 'res-sfc-10', report_id: 'rep-001', parameter_id: 'param-sfc', parameter_code: 'SFC', parameter_name: 'SFC @ 10°C', unit: '%', series_key: 10, requested: true, value_numeric: 51.5, in_spec: true },
      { id: 'res-sfc-20', report_id: 'rep-001', parameter_id: 'param-sfc', parameter_code: 'SFC', parameter_name: 'SFC @ 20°C', unit: '%', series_key: 20, requested: true, value_numeric: 26.8, in_spec: true },
      { id: 'res-sfc-30', report_id: 'rep-001', parameter_id: 'param-sfc', parameter_code: 'SFC', parameter_name: 'SFC @ 30°C', unit: '%', series_key: 30, requested: true, value_numeric: 7.9, in_spec: true },
      { id: 'res-sfc-35', report_id: 'rep-001', parameter_id: 'param-sfc', parameter_code: 'SFC', parameter_name: 'SFC @ 35°C', unit: '%', series_key: 35, requested: true, value_numeric: 0.4, in_spec: true },
    ],
    decision: {
      id: 'dec-001',
      report_id: 'rep-001',
      decision: 'accept',
      reason_id: null,
      reason_label: null,
      reason_detail: null,
      failed_parameters: [],
      disposition: null,
      decided_by: 'p-qc-01',
      decided_by_name: 'Siti Nurhaliza',
      decided_at: '2026-09-20T08:15:00+08:00',
    }
  },
  {
    id: 'rep-002',
    plant_id: INITIAL_PLANT.id,
    report_no: 'SAR-2026-000482',
    sample_date: '2026-09-20',
    time_check: '09:15',
    lot_no: 'LOT-PL65-2609-02',
    product_id: 'prod-26',
    product_name: 'PL 65 Matsuyama',
    product_other: null,
    feed_tank_id: 'tank-02',
    feed_tank_code: 'TK-101B',
    discharge_tank_id: 'tank-05',
    discharge_tank_code: 'TK-201B',
    crystallizer_no: 'CR-04',
    batch_no: 'B260902',
    sampling_point_id: 'sp-02',
    sampling_point_name: 'Tray 7 Final Sampling Cock',
    submitted_by: 'p-op-01',
    submitted_by_name: 'Ahmad Razak',
    remark_flushing: false,
    remark_cooling: false,
    remark_pushover: false,
    remarks: 'Sample drawn during vacuum excursion at 0900.',
    status: 'decided',
    created_by: 'p-op-01',
    created_at: '2026-09-20T09:20:00+08:00',
    results: [
      { id: 'res-21', report_id: 'rep-002', parameter_id: 'param-ffa', parameter_code: 'FFA', parameter_name: 'Free Fatty Acid', unit: '%', requested: true, value_numeric: 0.068, in_spec: false }, // Above 0.05
      { id: 'res-22', report_id: 'rep-002', parameter_id: 'param-h2o', parameter_code: 'H2O', parameter_name: 'Moisture & Impurities', unit: '%', requested: true, value_numeric: 0.024, in_spec: true },
      { id: 'res-23', report_id: 'rep-002', parameter_id: 'param-iv', parameter_code: 'IV', parameter_name: 'Iodine Value', unit: 'g I₂/100g', requested: true, value_numeric: 65.1, in_spec: true },
      { id: 'res-24', report_id: 'rep-002', parameter_id: 'param-pv', parameter_code: 'PV', parameter_name: 'Peroxide Value', unit: 'meq/kg', requested: true, value_numeric: 0.45, in_spec: true },
      { id: 'res-25', report_id: 'rep-002', parameter_id: 'param-col-r', parameter_code: 'COLOUR_R', parameter_name: 'Colour Red', unit: 'R', requested: true, value_numeric: 3.2, in_spec: false }, // Above 2.5
      { id: 'res-26', report_id: 'rep-002', parameter_id: 'param-col-y', parameter_code: 'COLOUR_Y', parameter_name: 'Colour Yellow', unit: 'Y', requested: true, value_numeric: 28.0, in_spec: false }, // Above 25.0
      { id: 'res-27', report_id: 'rep-002', parameter_id: 'param-odour', parameter_code: 'ODOUR', parameter_name: 'Odour Assessment', unit: null, requested: true, value_text: 'off', in_spec: false },
    ],
    decision: {
      id: 'dec-002',
      report_id: 'rep-002',
      decision: 'reject',
      reason_id: 'rej-04',
      reason_label: 'Colour out of specification',
      reason_detail: 'Colour Red 3.2R exceeds 2.5R maximum spec. Noticeable burnt odour due to 0900 vacuum loss.',
      failed_parameters: ['FFA (0.068%)', 'COLOUR_R (3.2R)', 'COLOUR_Y (28.0Y)', 'ODOUR (off)'],
      disposition: 'reprocess',
      decided_by: 'p-qcm-01',
      decided_by_name: 'Dr. Tan Keng Boon',
      decided_at: '2026-09-20T10:15:00+08:00',
    }
  },
  {
    id: 'rep-003',
    plant_id: INITIAL_PLANT.id,
    report_no: 'SAR-2026-000483',
    sample_date: '2026-09-20',
    time_check: '11:00',
    lot_no: 'LOT-PL65-2609-03',
    product_id: 'prod-26',
    product_name: 'PL 65 Matsuyama',
    product_other: null,
    feed_tank_id: 'tank-01',
    feed_tank_code: 'TK-101A',
    discharge_tank_id: 'tank-04',
    discharge_tank_code: 'TK-201A',
    crystallizer_no: 'CR-04',
    batch_no: 'B260903',
    sampling_point_id: 'sp-03',
    sampling_point_name: 'Cooler BC-101 Discharge Line',
    submitted_by: 'p-op-01',
    submitted_by_name: 'Ahmad Razak',
    remark_flushing: false,
    remark_cooling: false,
    remark_pushover: false,
    remarks: 'Post-adjustment verification sample.',
    status: 'awaiting_results',
    created_by: 'p-op-01',
    created_at: '2026-09-20T11:05:00+08:00',
    results: [
      { id: 'res-31', report_id: 'rep-003', parameter_id: 'param-ffa', parameter_code: 'FFA', parameter_name: 'Free Fatty Acid', unit: '%', requested: true },
      { id: 'res-32', report_id: 'rep-003', parameter_id: 'param-h2o', parameter_code: 'H2O', parameter_name: 'Moisture & Impurities', unit: '%', requested: true },
      { id: 'res-33', report_id: 'rep-003', parameter_id: 'param-col-r', parameter_code: 'COLOUR_R', parameter_name: 'Colour Red', unit: 'R', requested: true },
      { id: 'res-34', report_id: 'rep-003', parameter_id: 'param-odour', parameter_code: 'ODOUR', parameter_name: 'Odour Assessment', unit: null, requested: true },
    ]
  }
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 1,
    table_name: 'process_sheets',
    record_id: 'sheet-today-001',
    action: 'insert',
    actor_name: 'Ahmad Razak (Lead Operator)',
    new_row: { shift_date: '2026-09-20', stripping_steam_pct: 1.5, set_steam_supply_bar: 3.0, status: 'open' },
    occurred_at: '2026-09-20T06:55:00+08:00',
  },
  {
    id: 2,
    table_name: 'process_entries',
    record_id: 'entry-02',
    action: 'insert',
    actor_name: 'Ahmad Razak (Lead Operator)',
    new_row: { slot_label: '0900', vacuum_torr: 4.8, has_deviation: true },
    occurred_at: '2026-09-20T09:03:00+08:00',
  },
  {
    id: 3,
    table_name: 'qc_decisions',
    record_id: 'dec-002',
    action: 'insert',
    actor_name: 'Dr. Tan Keng Boon (QC Manager)',
    new_row: { decision: 'reject', reason: 'Colour out of specification', disposition: 'reprocess' },
    occurred_at: '2026-09-20T10:15:00+08:00',
  },
];
